phrase:
  project_id: 0acc93b3e9428948351feec377e3f408
  push:
    sources:
      - file: ./app/locales/<locale_name>.json
        params:
          file_format: react_simple_json
  pull:
    targets:
      - file: ./app/locales/<locale_name>.json
        params:
          file_format: react_simple_json
