phraseapp:
  access_token: c7475fd7ddc459ea3c937851a5a8c57480be8480b08a8c687540d485b82e162a
  project_id: d555f683709878b7734f25209fb081ff
  file_format: react_simple_json
  push:
    sources:
      - file: ./app/locales/en.json
        params:
          locale_id: en
          update_translations: true
      - file: ./app/locales/de.json
        params:
          locale_id: de
          # update_translations: true
      - file: ./app/locales/fr.json
        params:
          locale_id: fr
          # update_translations: true
      - file: ./app/locales/it.json
        params:
          locale_id: it
          # update_translations: true
  pull:
    targets:
      - file: ./app/locales/<locale_code>.json
