const coins = {
  KANGAROO: 'KANGAROO',
  KRUGERRAND: 'KRUGERRAND',
  CANADIAN_LEAF: 'CANADIAN_LEAF',
  BRITANNIA: 'BRITANNIA',
  VIENNA_PHILHARMONICS: 'VIENNA_PHILHARMONICS',
  AMERICAN_EAGLE: 'AMERICAN_EAGLE',
  AMERICAN_BUFFALO: 'AMERICAN_BUFFALO'
}

export {coins}
